//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.1

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "object")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub instance_of: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::concept::Entity",
        from = "Column::InstanceOf",
        to = "super::concept::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Concept,
    #[sea_orm(has_many = "super::delivery::Entity")]
    Delivery,
}

impl Related<super::concept::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Concept.def()
    }
}

impl Related<super::delivery::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Delivery.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
