//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

pub use super::consumption::Entity as Consumption;
pub use super::product::Entity as Product;
pub use super::purchase::Entity as Purchase;
pub use super::session::Entity as Session;
