//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "product")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub gtin: Option<i32>,
    #[sea_orm(unique)]
    pub name: Option<String>,
    pub default_price: i32,
    pub created_at: TimeDateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::consumption::Entity")]
    Consumption,
    #[sea_orm(has_many = "super::purchase::Entity")]
    Purchase,
}

impl Related<super::consumption::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Consumption.def()
    }
}

impl Related<super::purchase::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Purchase.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
